language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
env:
  - TEST_CMD="coverage run tests/test_snldata.py"
install:
  - pip install coverage coveralls pre-commit
  - pip install -e '.[d]'
script:
  - $TEST_CMD
after_success:
  - coveralls
notifications:
  on_success: change
  on_failure: always
matrix:
  include:
    - name: "lint"
      python: 3.7
      env:
        - TEST_CMD="pre-commit run --all-files"
    - name: "3.6"
      python: 3.6
    - name: "3.7"
      python: 3.7
    - name: "3.8"
      python: 3.8
before_deploy:
  - pip install pyinstaller
deploy:
  provider: releases
  skip_cleanup: true
  on:
    condition: $TRAVIS_PYTHON_VERSION == '3.6'
    repo: DiFronzo/SnlData
    tags: true
